management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # health,info,prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  shutdown: graceful

app:
  message: this is a message from application.yml file

spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
        period: 5000
        strategy: restart_context
      client:
        namespace: example-spring-cloud-kubernetes-hello-world
#      discovery:
#        all-namespaces: true
