server:
  port: 8011


app:
  clients:
    movie: http://localhost:8012

example-spring-cloud-kubernetes-server-movie:
  ribbon:
    listOfServers: http://localhost:8012

spring:
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
