management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  shutdown: graceful

spring:
  profiles:
    active:
    - dev
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
        period: 5000
        strategy: restart_context
      client:
        namespace: example-spring-cloud-kubernetes
feign:
  circuitbreaker:
    enabled: true

resilience4j:
  # 熔断器
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 4
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
      someShared:
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 10

    instances:
      example-spring-cloud-kubernetes-server-movie:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 3s
        slowCallDurationThreshold: 3s
        maxWaitDurationInHalfOpenState: 3s
        exponentialMaxWaitDurationInOpenState: 3s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  #      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        slidingWindowSize: 4
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
      someShared:
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 10
    instances:
      example-spring-cloud-kubernetes-server-movie:
        timeoutDuration: 2s
        cancelRunningFuture: true

logging:
  level:
    io.github.resilience4j: trace
    org.springframework.cloud.circuitbreaker: trace
