app:
  clients:
    movie: example-spring-cloud-kubernetes-server-movie.${spring.cloud.kubernetes.namespace}.svc.cluster.local:8080

spring:
  data:
    mongodb:
      host: mongodb.${spring.cloud.kubernetes.namespace}.svc.cluster.local
      port: 27017
      database: konga
      username: test
      password: test
