app:
  clients:
    account: example-spring-cloud-kubernetes-server-account.${spring.cloud.kubernetes.namespace}.svc.cluster.local:8080


spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: konga
      username: test
      password: test
