apiVersion: v1
kind: ConfigMap
metadata:
  name: konga
  namespace: example-spring-cloud-kubernetes
data:
  db-adapter: mongo

---
apiVersion: v1
kind: Secret
metadata:
  name: konga
  namespace: example-spring-cloud-kubernetes
type: Opaque
data:
  database-host: bW9uZ29kYi5leGFtcGxlLXNwcmluZy1jbG91ZC1rdWJlcm5ldGVzLnN2Yy5jbHVzdGVyLmxvY2Fs # mongodb.example-spring-cloud-kubernetes.svc.cluster.local
  database-name: YWRtaW4= # admin
  database-user: dGVzdA== # test
  database-password: dGVzdDEyMw== # test123
  token-secret: dGVzdDEyMw== # test123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: example-spring-cloud-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga
          env:
            - name: DB_ADAPTER
              valueFrom:
                configMapKeyRef:
                  name: konga
                  key: db-adapter
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: konga
                  key: database-host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: konga
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: konga
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: konga
                  key: database-password
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: konga
                  key: token-secret
          ports:
            - containerPort: 1337
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga
  namespace: example-spring-cloud-kubernetes
spec:
  ports:
    - protocol: TCP
      name: http
      port: 1337
      targetPort: 1337
  selector:
    app: konga
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: konga
  namespace: example-spring-cloud-kubernetes
spec:
  rules:
    - host: konga.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: konga
                port:
                  number: 1337

#  tls:
#    - hosts:
#        - konga.mydomain.com
#      secretName: konga-mydomain-tls
#kubetpl render konga.yml -i kong-env.yml --syntax go-template  | kubectl apply -f -
