apiVersion: v1
kind: Service
metadata:
  name: example-spring-cloud-kubernetes-server-account
  namespace: example-spring-cloud-kubernetes
  labels:
    app: example-spring-cloud-kubernetes-server-account
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: example-spring-cloud-kubernetes-server-account
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-spring-cloud-kubernetes-server-account
  namespace: example-spring-cloud-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-spring-cloud-kubernetes-server-account
  template:
    metadata:
      labels:
        app: example-spring-cloud-kubernetes-server-account
    spec:
      # hostNetwork: true # 使用hostNetwork暴露服务
      containers:
        - name: example-spring-cloud-kubernetes-server-account
          image: toquery/example-spring-cloud-kubernetes-server-account:0.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
