apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels:
    type: local
    name: config-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yenchu/git/microservices-demo/config-server/src/main/resources/shared"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      name: "config-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
