apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
    - port: 9411
  selector:
    app: zipkin
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: 192.168.99.100:5000/zipkin
        ports:
        - containerPort: 9411
        env:
        - name: RABBIT_ADDRESSES
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: rabbitmq-host
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: rabbitmq-user
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: rabbitmq-pwd
