---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: example-spring-cloud-kubernetes
  name: example-spring-cloud-kubernetes-hello-world
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-spring-cloud-kubernetes-hello-world
  namespace: example-spring-cloud-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-spring-cloud-kubernetes-hello-world
  namespace: example-spring-cloud-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-spring-cloud-kubernetes-hello-world
subjects:
  - kind: ServiceAccount
    name: example-spring-cloud-kubernetes-hello-world
    namespace: example-spring-cloud-kubernetes

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-spring-cloud-kubernetes-hello-world
  namespace: example-spring-cloud-kubernetes
data:
  application.yml: |-
    app.message=this is a message from kubernetes config map

