management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 8092
spring:
  main:
    allow-bean-definition-overriding: true
