apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    app: movie-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: toquery/example-spring-cloud-kubernetes-server-movie:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8081
        env:
        - name: SPRING-ACTIVE-PROFILES
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: spring-active-profiles

