apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  type: NodePort
  ports:
    - port: 8761
  selector:
    app: service-registry
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: 192.168.99.100:5000/service-registry
        ports:
        - containerPort: 8761
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: config-server-url
        volumeMounts:
        - name: log-vol
          mountPath: /var/log/msdemo
      volumes:
      - name: log-vol
        persistentVolumeClaim:
          claimName: log-claim
