management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 8090

spring:
  security:
    user:
      name: admin
      password: admin
      roles: admin
  boot:
    admin:
      context-path: /
      discovery:
        converter:
          management-context-path: manage

