management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 8090

spring:
  boot:
    admin:
      context-path: /admin
      discovery:
        converter:
          management-context-path: manage
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        #service-labels:
        #  spring-boot: true
