management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  shutdown: graceful

app:
  message: this is a message from yml file

#spring:
#  cloud:
#    kubernetes:
#      client:
#        masterUrl: https://localhost:6443
